name: iCaiu Sync

on:
  repository_dispatch:
    types: [icaiu_report_ready]
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: npm install axios
      
      - name: Execute Sync
        run: |
          printf "::add-mask::%s\n" "$GOOGLE_TOKEN"
          node sync-icaiu.js
        env:
          GOOGLE_TOKEN: ${{ github.event.client_payload.token }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_ACCOUNT_OWNER: ${{ secrets.ZOHO_ACCOUNT_OWNER }}
          REPORT_COLUMN_MAPPING: ${{ secrets.REPORT_COLUMN_MAPPING }}
          REPORT_SPREADSHEET_ID: ${{ secrets.REPORT_SPREADSHEET_ID }}
          REPORT_SHEET_NAME: ${{ secrets.REPORT_SHEET_NAME }}
          ZOHO_APP_NAME: ${{ secrets.ZOHO_APP_ICAIU }}
          ZOHO_REPORT_NAME: ${{ secrets.ZOHO_REPORT_ICAIU }}
