name: Transfer Secrets
on: workflow_dispatch

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer
        env:
          GH_TOKEN: ${{ secrets.TRANSFER_TOKEN }}
          DEST_REPO: "operacoesicaiu/icaiu-data"
          # Variáveis de Origem (Leads)
          COLUMN_MAPPING: ${{ secrets.COLUMN_MAPPING }}
          ZOHO_REPORT_LINK_NAME: ${{ secrets.ZOHO_REPORT_LINK_NAME }}
          ZOHO_APP_LINK_NAME: ${{ secrets.ZOHO_APP_LINK_NAME }}
          # Variáveis de Origem (Agendamentos)
          REPORT_COLUMN_MAPPING: ${{ secrets.REPORT_COLUMN_MAPPING }}
          ZOHO_REPORT_NAME: ${{ secrets.ZOHO_REPORT_NAME }}
          ZOHO_APP_NAME: ${{ secrets.ZOHO_APP_NAME }}
          # Variáveis Gerais de Conexão
          ZOHO_ACCOUNT_OWNER: ${{ secrets.ZOHO_ACCOUNT_OWNER }}
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
        run: |
          # --- Leads (Renomeação) ---
          gh secret set ZOHO_LEADS_COLUMN_MAPPING --repo "$DEST_REPO" --body "$COLUMN_MAPPING"
          gh secret set ZOHO_LEADS_REPORT_NAME --repo "$DEST_REPO" --body "$ZOHO_REPORT_LINK_NAME"
          gh secret set ZOHO_LEADS_APP_NAME --repo "$DEST_REPO" --body "$ZOHO_APP_LINK_NAME"

          # --- Agendamentos (Renomeação) ---
          gh secret set ZOHO_SCHEDULING_COLUMN_MAPPING --repo "$DEST_REPO" --body "$REPORT_COLUMN_MAPPING"
          gh secret set ZOHO_SCHEDULING_REPORT_NAME --repo "$DEST_REPO" --body "$ZOHO_REPORT_NAME"
          gh secret set ZOHO_SCHEDULING_APP_NAME --repo "$DEST_REPO" --body "$ZOHO_APP_NAME"

          # --- Gerais (Mantêm o nome original) ---
          gh secret set ZOHO_ACCOUNT_OWNER --repo "$DEST_REPO" --body "$ZOHO_ACCOUNT_OWNER"
          gh secret set ZOHO_CLIENT_ID --repo "$DEST_REPO" --body "$ZOHO_CLIENT_ID"
          gh secret set ZOHO_CLIENT_SECRET --repo "$DEST_REPO" --body "$ZOHO_CLIENT_SECRET"
          gh secret set ZOHO_REFRESH_TOKEN --repo "$DEST_REPO" --body "$ZOHO_REFRESH_TOKEN"
